version: '3'

services:

  #docker run -it --rm -p 2015:2015 -v $(pwd)/data:/db --name websql acttaiwan/phpliteadmin
  #https://hub.docker.com/r/vtacquet/phpliteadmin
  
  #docker compose up websqlite
  websqlite:
    profiles: [ 'websqlite' ]
    container_name: websqlite
    image: vtacquet/phpliteadmin
    restart: unless-stopped
    volumes:
      - ./:/db/
    ports:
      - "2015:80"
    environment:
      - TZ=America/Sao_Paulo
      - PASSWORD=admin
      - LOCATION=/db

  #docker compose up
  run:
    image: ${IMAGE}
    ports:
      - "8000:8000"
    volumes:
      - ./:/data
    working_dir: /data/src
    command: python3 /data/src/base/manage.py runserver 0.0.0.0:8000

  #docker compose run bash
  bash:
    image: ${IMAGE}
    profiles: [ 'bash' ]
    stdin_open: true
    tty: true
    volumes:
      - ./:/data
    working_dir: /data
    command: /bin/bash
